import { Metadata } from "next";
import Link from "next/link";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";

export const metadata: Metadata = {
  title: "Meditation & Mindfulness — Dhyana, Sound Baths & Mental Wellbeing | AyurPass",
  description:
    "Explore sound bath healing, Vipassana silent meditation, Yoga Nidra, breathwork workshops, and accredited meditation centers near you.",
};

const MODALITIES = [
  {
    title: "Sound Bath & Himalayan Bowls",
    desc: "Harmonic frequencies generated by crystal and Tibetan singing bowls induce deep theta brainwaves, releasing physical tension and emotional blockages.",
    image: "https://picsum.photos/seed/ayur16/1200/800",
  },
  {
    title: "Yoga Nidra (Psychic Sleep)",
    desc: "A guided systematic relaxation practice bringing you to the border of sleep and wakefulness. 45 minutes of Yoga Nidra equals 3 hours of deep restful sleep.",
    image: "https://picsum.photos/seed/ayur17/1200/800",
  },
  {
    title: "Vipassana & Silent Retreats",
    desc: "Ancient insight meditation practice focusing on non-judgmental observation of bodily sensations, mental states, and impermanence.",
    image: "https://picsum.photos/seed/ayur18/1200/800",
  },
  {
    title: "Somatic Breathwork",
    desc: "Conscious connected breathing techniques that stimulate the vagus nerve, flush stress hormones, and recalibrate emotional vitality.",
    image: "https://picsum.photos/seed/ayur19/1200/800",
  },
];

export default function MeditationPage() {
  return (
    <div className="flex min-h-screen flex-col bg-background text-foreground">
      <Navbar />

      <main className="flex-1">
        {/* Hero Section */}
        <section className="relative min-h-[480px] overflow-hidden bg-surface">
          <img
            src="/images/heroes/meditation.png"
            alt="Meditation Practice"
            className="absolute inset-0 h-full w-full object-cover opacity-60"
          />
          <div className="absolute inset-0 bg-gradient-to-r from-white/60 via-white/30 to-transparent" />

          <div className="relative mx-auto flex max-w-6xl flex-col justify-center px-[var(--space-page-x)] py-20 sm:py-28">
            <span className="inline-flex w-fit items-center gap-2 rounded-full border border-forest/20 bg-white/80 px-3.5 py-1 text-xs font-semibold uppercase tracking-wider text-forest" style={{  boxShadow: "0 0 10px rgba(255,255,255,0.8)"  }}>
              🍃 Mindful Stillness & Dhyana
            </span>
            <h1 className="mt-4 font-display text-4xl font-bold tracking-tight text-forest sm:text-6xl sm:leading-tight" style={{ textShadow: "0 0 20px rgba(255,255,255,1), 0 0 10px rgba(255,255,255,0.8)" }}>
              Meditation — Cultivate Inner Clarity
            </h1>
            <p className="mt-5 max-w-2xl text-base font-semibold leading-relaxed text-ink-secondary sm:text-lg" style={{ textShadow: "0 0 15px rgba(255,255,255,1), 0 0 5px rgba(255,255,255,0.8)" }}>
              Calm the chatter of the mind and awaken deep intuitive presence. Discover sound bath
              sanctuaries, guided breathwork, and silent retreat centers.
            </p>
            <div className="mt-8 flex flex-wrap gap-3">
              <Link
                href="/discover?group=Meditation"
                className="inline-flex min-h-12 items-center rounded-full bg-gold px-7 py-3 text-sm font-semibold text-forest-deep transition-colors hover:bg-goldSoft"
              >
                Find Meditation Sanctuaries
              </Link>
            </div>
          </div>
        </section>

        {/* Modalities */}
        <section className="py-16 sm:py-24">
          <div className="mx-auto max-w-6xl px-[var(--space-page-x)]">
            <div className="mx-auto max-w-3xl text-center">
              <span className="text-xs font-bold uppercase tracking-widest text-leaf">
                MEDITATION MODALITIES
              </span>
              <h2 className="mt-2 font-display text-3xl font-bold text-forest sm:text-4xl">
                Restorative Mental Practices
              </h2>
            </div>

            <div className="mt-12 grid gap-8 md:grid-cols-2">
              {MODALITIES.map((m) => (
                <div
                  key={m.title}
                  className="group overflow-hidden rounded-3xl border border-hairline bg-surface p-6 sm:p-8 flex flex-col justify-between"
                >
                  <div>
                    <h3 className="font-display text-2xl font-bold text-forest">{m.title}</h3>
                    <p className="mt-3 text-sm leading-relaxed text-ink-secondary">{m.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA */}
        <section className="border-t border-hairline bg-forest py-16 text-white sm:py-20">
          <div className="mx-auto max-w-4xl px-[var(--space-page-x)] text-center">
            <h2 className="font-display text-3xl font-bold sm:text-4xl">
              Begin Your Mindfulness Journey
            </h2>
            <p className="mx-auto mt-4 max-w-xl text-base text-goldSoft">
              Book sound healing sessions, breathwork workshops, or guided meditation circles with AyurPass.
            </p>
            <div className="mt-8 flex justify-center">
              <Link
                href="/discover?group=Meditation"
                className="inline-flex min-h-12 items-center rounded-full bg-gold px-7 py-3 text-sm font-semibold text-forest-deep transition-colors hover:bg-goldSoft"
              >
                Browse Meditation Centers
              </Link>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </div>
  );
}
